// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:uscitylink/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChannelAdapter());
    registerAdapter(ChannelModelAdapter());
    registerAdapter(CountModelAdapter());
    registerAdapter(DashboardModelAdapter());
    registerAdapter(GroupAdapter());
    registerAdapter(GroupChannelAdapter());
    registerAdapter(GroupDashboardAdapter());
    registerAdapter(GroupModelAdapter());
    registerAdapter(LatestGroupMessageAdapter());
    registerAdapter(LatestMessageAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(SenderModelAdapter());
    registerAdapter(UserChannelModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
